# Generated by Django 3.1.5 on 2022-06-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_charged', models.CharField(max_length=45)),
                ('mnth', models.CharField(blank=True, max_length=12)),
                ('yr', models.CharField(blank=True, max_length=4)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
