# Generated by Django 3.1.5 on 2022-06-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
