# Generated by Django 4.0.3 on 2022-06-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=12)),
                ('transaction_detail', models.CharField(max_length=100)),
                ('amount', models.CharField(blank=True, max_length=12)),
                ('curr_balance', models.CharField(default=0, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContributionAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrib_acct_transaction_type', models.CharField(max_length=12)),
                ('contrib_acct_transaction_detail', models.CharField(max_length=100)),
                ('contrib_acct_amount', models.CharField(blank=True, max_length=12)),
                ('contrib_acct_curr_balance', models.CharField(default=0, max_length=45)),
                ('contrib_acct_created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
