# Generated by Django 4.0.3 on 2022-06-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='amount',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
