# Generated by Django 4.0.3 on 2022-06-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_companyaccount_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyAccount',
            new_name='Company_account',
        ),
        migrations.RenameModel(
            old_name='ContributionAccount',
            new_name='Contribution_account',
        ),
    ]
