# Generated by Django 3.1.5 on 2022-09-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_companyaccount_company_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_total_funds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(default=0, max_length=12)),
                ('contrib_acct_created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
