# Generated by Django 3.1.5 on 2022-09-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_admin_total_funds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_total_funds',
            name='contrib_acct_created_at',
        ),
    ]
