# Generated by Django 3.1.5 on 2022-06-12 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('gender', models.CharField(blank=True, max_length=6)),
                ('tel', models.CharField(blank=True, max_length=12)),
                ('home_addr', models.CharField(blank=True, max_length=150)),
                ('acct_bank', models.CharField(blank=True, max_length=50, null=True)),
                ('acct_name', models.CharField(blank=True, max_length=100, null=True)),
                ('acct_no', models.CharField(blank=True, max_length=15, null=True)),
                ('kin_name', models.CharField(blank=True, max_length=45)),
                ('kin_tel', models.CharField(blank=True, max_length=15)),
                ('kin_relationship', models.CharField(blank=True, max_length=15)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Teller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('gender', models.CharField(blank=True, max_length=6)),
                ('tel', models.CharField(blank=True, max_length=12)),
                ('home_addr', models.CharField(blank=True, max_length=150)),
                ('acct_bank', models.CharField(blank=True, max_length=50, null=True)),
                ('acct_name', models.CharField(blank=True, max_length=100, null=True)),
                ('acct_no', models.CharField(blank=True, max_length=15, null=True)),
                ('kin_name', models.CharField(blank=True, max_length=45)),
                ('kin_tel', models.CharField(blank=True, max_length=15)),
                ('kin_relationship', models.CharField(blank=True, max_length=15)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('gender', models.CharField(blank=True, max_length=6)),
                ('tel', models.CharField(blank=True, max_length=12)),
                ('branch', models.CharField(blank=True, max_length=50)),
                ('package', models.CharField(blank=True, max_length=50)),
                ('business_addr', models.CharField(blank=True, max_length=150, null=True)),
                ('home_addr', models.CharField(blank=True, max_length=150)),
                ('acct_bank', models.CharField(blank=True, max_length=50, null=True)),
                ('acct_name', models.CharField(blank=True, max_length=100, null=True)),
                ('acct_no', models.CharField(blank=True, max_length=15, null=True)),
                ('kin_name', models.CharField(blank=True, max_length=45)),
                ('kin_tel', models.CharField(blank=True, max_length=15)),
                ('kin_relationship', models.CharField(blank=True, max_length=15)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
