# Generated by Django 3.1.5 on 2022-06-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_plan',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
