# Generated by Django 3.1.5 on 2022-06-12 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dir', models.BooleanField(default=False)),
                ('is_mgr', models.BooleanField(default=False)),
                ('is_teller', models.BooleanField(default=False)),
                ('is_cust', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=35, null=True)),
                ('last_name', models.CharField(blank=True, max_length=35, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
