# Generated by Django 3.1.5 on 2022-06-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cust_contrb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(default=0, max_length=15)),
                ('charges', models.CharField(default=0, max_length=15)),
                ('total', models.CharField(default=0, max_length=15)),
                ('wallet', models.CharField(default=0, max_length=15)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cust_contrb', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=50)),
                ('amount', models.CharField(blank=True, max_length=15, null=True)),
                ('payment_date', models.CharField(blank=True, max_length=15, null=True)),
                ('staff_incharge', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution', to='customer.customer')),
            ],
        ),
    ]
