# Generated by Django 3.1.5 on 2022-06-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='staff_incharge',
            new_name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='contribution',
            name='contribution_date',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='payment_plan',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
