# Generated by Django 3.1.5 on 2022-06-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_auto_20220617_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contributn_date',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
