# Generated by Django 3.1.5 on 2022-06-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0003_contribution_contributn_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='contributn_date',
        ),
    ]
