# Generated by Django 3.1.5 on 2022-06-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0004_remove_contribution_contributn_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='contribution_date',
        ),
        migrations.AddField(
            model_name='contribution',
            name='contribution_day',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='contribution_month',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='contribution_year',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
