# Generated by Django 3.1.5 on 2022-06-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0005_auto_20220619_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_contrb',
            name='contribution_period',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
