# Generated by Django 3.1.5 on 2022-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0006_cust_contrb_contribution_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_contrb',
            name='set_current_contrib_period',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
