# Generated by Django 3.1.5 on 2022-06-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0007_cust_contrb_set_current_contrib_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_charged', models.CharField(max_length=45)),
                ('contribution_month', models.CharField(blank=True, max_length=12)),
                ('contribution_year', models.CharField(blank=True, max_length=4)),
            ],
        ),
    ]
