# Generated by Django 3.1.5 on 2022-06-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0008_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_contrb',
            name='deducted_commission_for',
            field=models.CharField(default=0, max_length=35),
        ),
    ]
