# Generated by Django 3.1.5 on 2022-09-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0009_cust_contrb_deducted_commission_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_contrb',
            name='charges',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cust_contrb',
            name='contribution_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cust_contrb',
            name='deducted_commission_for',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='cust_contrb',
            name='duration',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cust_contrb',
            name='set_current_contrib_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cust_contrb',
            name='total',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cust_contrb',
            name='wallet',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
