# Generated by Django 3.1.5 on 2022-09-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0010_auto_20220906_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_contrb',
            name='charges',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='cust_contrb',
            name='contribution_period',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='cust_contrb',
            name='deducted_commission_for',
            field=models.CharField(default=0, max_length=35),
        ),
        migrations.AlterField(
            model_name='cust_contrb',
            name='duration',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='cust_contrb',
            name='set_current_contrib_period',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='cust_contrb',
            name='total',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='cust_contrb',
            name='wallet',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
