# Generated by Django 3.1.5 on 2022-09-07 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_payment_plan'),
        ('contribution', '0011_auto_20220906_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=15, null=True)),
                ('withdrawal_date', models.CharField(blank=True, max_length=15, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal', to='customer.customer')),
            ],
        ),
    ]
